<a href="https://colab.research.google.com/github/Sam4719y/ml-projects-/blob/main/encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#nominal/ohe encoder
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df = pd.DataFrame({
    'color':['red','blue','green','green','red','blue']
})

In [ ]:
encoder = OneHotEncoder()
encoder.fit_transform(df[["color"]]).toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [ ]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encoder.fit_transform(df[["color"]])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [ ]:
encoder.transform([['red']])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [ ]:
#ordinal encioding
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({
    "size": ["small","medium","large","medium","small","large"]
})
encoder = OrdinalEncoder(categories = [["small","medium","large"]])
encoder.fit_transform(df[["size"]])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [ ]:
#target ordinal encoding
import pandas as pd
df = pd.DataFrame({
    'city': ['New York','London','Tokyo','New York','Paris'],
    'price': [200,150,300,250,320]
})
df

       city  price
0  New York    200
1    London    150
2     Tokyo    300
3  New York    250
4     Paris    320

In [ ]:
mean_price = df.groupby("city")["price"].mean()
df

       city  price  city_encoded
0  New York    200         225.0
1    London    150         150.0
2     Tokyo    300         300.0
3  New York    250         225.0
4     Paris    320         320.0

In [ ]:
df["city_encoded"] = df["city"].map(mean_price)
df

       city  price  city_encoded
0  New York    200         225.0
1    London    150         150.0
2     Tokyo    300         300.0
3  New York    250         225.0
4     Paris    320         320.0